project:
  name: Learn2Slither
  description: A snake game with neural network-based AI and multiplayer modes.
  version: "1.0.0"
  author: Federico Salazar Lois
  license: MIT
  repository: ""
  environment: Development

logging:
  level: info
  file: learn2slither.log

map:
  board_size:
    width: 20
    height: 20
  green_apples: 2
  red_apples: 1
  snakes: 2

snake:
  start_color: blue
  start_speed: 1
  start_size: 3
  max_speed: 5

visual:
  modes:
    mode: pygame
    available_modes:
      - cli
      - pygame
    control:
      - auto
      - manual
    multiplayer_modes:
      - free_for_all
      - team
  speed: normal
  themes:
    default_theme: dark
    available_themes:
      - light
      - dark

ascii:
  wall: W
  snake_head: H
  snake_body: S
  green_apple: G
  red_apple: R
  empty: "0"

pygame_textures:
  wall:
    dark: wall/wall_block_32_0.png
    light: wall/wall_light.png
  snake_head:
    dark: snake_head/snake_green_head_32.png
    light: snake_head/snake_head_light.png
  snake_body:
    dark: snake_body/snake_green_blob_32.png
    light: snake_body/snake_body_light.png
  green_apple:
    dark: green_apple/apple_green_32.png
    light: green_apple/green_apple_light.png
  red_apple:
    dark: red_apple/apple_red_32.png
    light: red_apple/red_apple_light.png
  empty:
    dark: empty/empty_dark.png
    light: empty/empty_light.png

rules:
  events:
    death: -10
    green_apple: 10
    red_apple: -5
  win_condition:
    condition: max_snake_size
    max_score: 1

nn:
  training:
    batch_size: 32
    epochs: 20000
    learning_rate: 0.001
    exploration:
      epsilon: 1.0
      decay: 0.95
      epsilon_min: 0.05
    gamma: 0.90
    
paths:
  models: models
  logs: logs
  outputs: outputs
  textures: resources/textures
