project:
  name: Learn2Slither
  description: A snake game with neural network-based AI and multiplayer modes.
  version: "1.0.0"
  author: Federico Salazar Lois
  license: MIT
  repository: ""
  environment: Development

logging:
  level: info
  file: learn2slither.log

map:
  board_size:
    width: 30
    height: 30
  green_apples: 2
  red_apples: 1

snake:
  start_size: 3
  difficulty:
    ai_easy: snake_brain_10.pth
    ai_medium: snake_brain_50.pth
    ai_hard: snake_brain_100.pth


visual:
  modes:
    mode: pygame
    available_modes:
      - cli
      - pygame
  themes:
    default_theme: dark
    available_themes:
      - light
      - dark

ascii:
  wall: W
  snake_head: H
  snake_body: S
  green_apple: G
  red_apple: R
  empty: "0"

pygame_textures:
  wall:
    dark: wall/wall_block_32_0.png
    light: wall/wall_block_32_0.png
  snake_head:
    dark: snake_head/snake_green_head_32.png
    light: snake_head/snake_yellow_head_32.png
  snake_body:
    dark: snake_body/snake_green_blob_32.png
    light: snake_body/snake_yellow_blob_32.png
  green_apple:
    dark: green_apple_alternate/oliebol_32.png
    light: green_apple/apple_green_32.png
  red_apple:
    dark: red_apple_alternate/bomb_32.png
    light: red_apple/apple_red_32.png
  empty:
    dark: empty/empty_dark.png
    light: empty/empty_light.png
  backgrounds:
    dark: backgrounds/splash_background_dark.png
    light: backgrounds/splash_background_light.png
  texture_size: 32

pygame_audio:
  home: home.mp3
  game: game.mp3

rules:
  events:
    death: -10
    green_apple: 1
    red_apple: -1
    looping: -1
    kill: 1
  steps_no_apple: 50
  win_condition:
    condition: max_snake_size
    max_score: 10

nn:
  batch_size: 64
  epochs: 1_000
  learning_rate: 0.001
  exploration:
    epsilon: 0.99
    decay: 0.99
    epsilon_min: 0.00
  gamma: 0.95
  update_frequency: 10
  input_shape: 28
  output_shape: 4
  memory_size: 200_000
  patience: 100
  min_delta: 0.001
    
paths:
  models: models
  logs: logs
  outputs: outputs
  textures: resources/textures
  audio: resources/audio
