services:
  learn2slither:
    image: learn2slither
    container_name: learn2slither
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/snd:/dev/snd
    networks:
      - default
    environment:
      - DISPLAY=$DISPLAY
      - /tmp/.X11-unix:/tmp/.X11-unix    
    restart: on-failure
    stdin_open: true
    tty: true

networks:
  default: